version: '3'

services:
  container:
    depends_on:
      - browse
      - content
      - restaurant-order
    image: node:16-alpine
    command: npm run start
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./container:/app
    working_dir: /app

  browse:
    image: node:16-alpine
    command: npm run start
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
    ports:
      - 3001:3001
    volumes:
      - ./browse:/app
    working_dir: /app

  content:
    image: node:16-alpine
    command: sh -c "npm run build && npm run start"
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
    ports:
      - 5000:5000
    volumes:
      - ./content:/app
    working_dir: /app

  restaurant-order:
    image: node:16-alpine
    command: npm run start
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
    ports:
      - 3002:3002
    volumes:
      - ./restaurant-order:/app
    working_dir: /app
